[package]
name = "pgx-s3sign"
version = "1.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg12"]
pg10 = ["pgx/pg10"]
pg11 = ["pgx/pg11"]
pg12 = ["pgx/pg12"]
pg_test = []

[dependencies]
pgx = "0.0.13"
pgx-macros = "0.0.13"
rust-s3 = "0.22.12"
aws-region = "0.21.0"
aws-creds = "0.22.2"
futures = "0.3.5"

[dev-dependencies]
pgx-tests = "0.0.13"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
